name: pytesting_legacy

on:
  push:
#    branches: [ main ]
  schedule:
    - cron: '0 0 1 * *'
# pull_request:
#    branches:
#      - '*'

jobs:
  run:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        python: ['3.7',]
    env:
      OS: ${{ matrix.os }}
      PYTHON: ${{ matrix.python }}
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    #- name: Lint with flake8
    #  run: |
    #    pip install flake8
    #    # stop the build if there are Python syntax errors or undefined names
    #    flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
    #    # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
    #    flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Build and compile
      run: |
        python setup.py develop
        #python setup.py sdist
    #    python setup.py build_ext --inplace
        
    - name: Test with pytest
      run: |
        pip install pytest
        pytest tests/test_tree_clf_and_reg.py
